from cip_protocol.cip import CIP, CIPResult
from cip_protocol.control import (
    ConstraintParser,
    ControlPreset,
    PolicyConflictResult,
    PresetRegistry,
    RunPolicy,
    detect_policy_conflict,
)
from cip_protocol.conversation import Conversation, Turn
from cip_protocol.data import (
    DataField,
    DataQuery,
    DataRequirement,
    DataResult,
    DataSchema,
    DataSource,
    DataSourceRegistry,
    DataSourceSpec,
    PrivacyClassification,
    PrivacyPolicy,
    ValidationResult,
)
from cip_protocol.domain import DomainConfig
from cip_protocol.engagement import (
    EscalationCallback,
    EscalationConfig,
    EscalationDetector,
    EscalationStore,
    LayeredScoreResult,
    LayerMapping,
    LeadEvent,
    LeadScoringConfig,
    check_escalation,
    clean_numeric_string,
    compute_lead_score,
    infer_lead_status,
    lead_score_band,
    parse_float,
    parse_int,
    parse_price,
    recency_multiplier,
    score_lead_with_layers,
)
from cip_protocol.llm.response import ArgumentStructureEvaluator, ManticSafetyEvaluator
from cip_protocol.mantic_adapter import (
    Backend,
    DetectionResult,
    FallacyResult,
    classify_fallacy,
    detect_argument_friction,
    detect_safety_friction,
    get_backend,
)
from cip_protocol.orchestration import (
    ProviderPool,
    build_cross_domain_context,
    build_raw_response,
    log_and_return_tool_error,
    run_tool_with_orchestration,
)
from cip_protocol.telemetry import (
    InMemoryTelemetrySink,
    LoggerTelemetrySink,
    NoOpTelemetrySink,
    TelemetryEvent,
    TelemetrySink,
)

__all__ = [
    "ArgumentStructureEvaluator",
    "Backend",
    "CIP",
    "CIPResult",
    "ConstraintParser",
    "ControlPreset",
    "Conversation",
    "DataField",
    "DataQuery",
    "DataRequirement",
    "DataResult",
    "DataSchema",
    "DataSource",
    "DataSourceRegistry",
    "DataSourceSpec",
    "DetectionResult",
    "DomainConfig",
    "EscalationCallback",
    "EscalationConfig",
    "EscalationDetector",
    "EscalationStore",
    "FallacyResult",
    "InMemoryTelemetrySink",
    "LayerMapping",
    "LayeredScoreResult",
    "LeadEvent",
    "LeadScoringConfig",
    "LoggerTelemetrySink",
    "ManticSafetyEvaluator",
    "NoOpTelemetrySink",
    "PolicyConflictResult",
    "PresetRegistry",
    "PrivacyClassification",
    "PrivacyPolicy",
    "ProviderPool",
    "RunPolicy",
    "TelemetryEvent",
    "TelemetrySink",
    "Turn",
    "ValidationResult",
    "build_cross_domain_context",
    "build_raw_response",
    "check_escalation",
    "classify_fallacy",
    "clean_numeric_string",
    "compute_lead_score",
    "detect_argument_friction",
    "detect_policy_conflict",
    "detect_safety_friction",
    "get_backend",
    "infer_lead_status",
    "lead_score_band",
    "log_and_return_tool_error",
    "parse_float",
    "parse_int",
    "parse_price",
    "recency_multiplier",
    "run_tool_with_orchestration",
    "score_lead_with_layers",
]
try:
    from importlib.metadata import version as _pkg_version

    __version__ = _pkg_version("cip-protocol")
except Exception:
    __version__ = "0.4.0"
